### ISSUE TITLE
Issue with the BB Bodice armhole

### ISSUE THREAD

**Issue by aharwood2** [aharwood2/JBlockCreator#7]
There is an issue with the upper half of the bodice armhole curve. See attached files. Needs debugging.
[A676FR39.txt](https://github.com/aharwood2/JBlock2D/files/1938022/A676FR39.txt)
[A676FR39_Bodice_Main_Block_DXF.txt](https://github.com/aharwood2/JBlock2D/files/1938026/A676FR39_Bodice_Main_Block_DXF.txt)

**Comment by jamesgill1997** [comment]
Issue seems to be with a measurement not linked to scan data rather than a method error.

**Comment by aharwood2** [comment]
Specifically, there is no custom measurement provided for the width of the armhole. Instead, the software has been using a default value from the Size 12 dress form which is far too small for most of the data provided. The only way this issue can be solved is to either add some logic ourselves to derive the measurement or wait until a custom measurement is available from the scan data repository.

**Comment by jamesgill1997** [comment]
Added a new measurement to use for the armhole. Any remaining errors with the pattern are as a result of the method being optimised for a size 12 and not giving adjustments to larger or slimmer people.

**Comment by aharwood2** [comment]
As this is not solved but might be in the future, I'll leave it open.

**Comment by aharwood2** [comment]
This is not a bug but simply a matter of not having the correct measurement for the armhole depth. This is not usually available from scanner data but could be supplied manually.

**Comment by aharwood2** [comment]
What we should do in future is have the software check for the presence of the correct measurement given in the input file (using the tag). If the measurement is not there, fall back on the approximation and print a warning in the log. That way, we can allow users to manually supply the measurement in the input file if necessary.

**Comment by scantopattern** [comment]
Potential fix in PR #61

**Comment by aharwood2** [comment]
We could always set the armhole width based on percentage of the total bust circumference.

**Comment by aharwood2** [comment]
We need to use the following to drive this: Scye is 11.5cm or 24.5% of 1/2 the total bust + ease

**Comment by aharwood2** [comment]
OK I've added this and removed the old rule. Seeking confirmation whether we are preferring the maximum of these two values or the minimum.
