### ISSUE TITLE
Extending the bezier functions to take angle arguments

### ISSUE THREAD

**Issue by MAhmed25** [aharwood2/JBlockCreator#82]

**Comment by aharwood2** [comment]
This will need looking into a bit as we need to see where the need is here and only add this feature if it is required.

**Comment by aharwood2** [comment]
There are quite a lot of overloads for the cubic spline curves here that we could emulate. For now, I've added a single overload which infers the directions of the sides from neighbouring key points then computes the control point so the curve is naturally blended. Closing for now until we work out whether we need any more or not.
